- src/components/Editor/Passage/index.tsx
- src/components/Editor/Toolbar/Buttons.tsx
- src/components/Editor/Toolbar/index.tsx
- src/components/Editor/index.tsx
Implemented Drag to Select feature and Deselect all button
modified the padding style for passageDivStyle to provide a better drag-select experience ( set the padding to <Passage /> instead to include more selectable areas on the margins )
> Pull Request 2024-05-23: Drag to Select Feature and Deselect All Button Online

- src/app/coming-soon/page.tsx
- src/app/layout.tsx
- src/app/page.tsx
- src/components/CountDownTimer/index.tsx
- src/middleware.ts
In this PR:
- added a coming soon page for [sela.biblepoetry.org](https://sela.biblepoetry.org/)
> feat: add coming soon page

- src/middleware.ts
In this PR:
- make view (public) study pages publicly accessible
> feat: make view public study page publicly accessible

- src/app/study/[id]/edit/layout.tsx
- src/components/StudyPane/Header/index.tsx
- src/components/StudyPane/InfoPane/index.tsx
- src/components/StudyPane/Passage/index.tsx
- src/components/StudyPane/Toolbar/index.tsx
- src/components/StudyPane/index.tsx
> Pull Request 2024-08-22: New toolbar UI updated

- src/components/StudyPane/Header/index.tsx
- src/components/StudyPane/InfoPane/index.tsx
- src/components/StudyPane/Passage/index.tsx
- src/components/StudyPane/Toolbar/index.tsx
- src/components/StudyPane/index.tsx
Fix issue: header bar disappear when user scroll down in long passages
> Pull Request 2024-08-22: Bug fix for header and sidebar

- src/components/CountDownTimer/index.tsx
update launch date to Jan 4th 25
> fix: update launch date to Jan 4th 25

- src/components/StudyPane/Toolbar/Buttons.tsx
- src/components/StudyPane/Toolbar/index.tsx
- src/styles/globals.css
Fix issue: toolbar is reversed under hebrew mode
> Pull Request 2024-09-07: Fix toolbar direction issue

- src/components/StudyPane/Passage/StropheBlock.tsx
- src/components/StudyPane/Passage/WordBlock.tsx
- src/components/StudyPane/Passage/index.tsx
- src/components/StudyPane/Toolbar/Buttons.tsx
- added functionality for collapsing individual strophes -- will need additional work to persist it in the backend
- bug fixes for drag select in safari
- bug fixes for drag and select after first colour changes done 
- cosmetic changes to selected wordBlocks and selected strophes
> Spacing edits

- src/components/StudyPane/Toolbar/ScaleDropDown.tsx
- fix scale calculation
- `.toPrecision(2)` will round up the scale value and cause the vertical scrollbar
- fix comment message
> fix: fit screen scroll bar bug

- src/components/StudyPane/InfoPane/Motif/Root.tsx
- src/components/StudyPane/InfoPane/Motif/index.tsx
- src/components/StudyPane/InfoPane/index.tsx
- src/components/StudyPane/Passage/index.tsx
- src/components/StudyPane/index.tsx
- src/hooks/useDragToSelect.tsx
Fixed bug: drag to select feature unable to cancel on mouse up when motif tab is on
Code update: Turned drag to select feature into a hook (useDragToSelect.tsx) for better code management
> Pull Request 2024-10-05 Fix drag-to-select bug, turn drag-to-select into a hook

- src/components/StudyPane/Header/index.tsx
- src/components/StudyPane/Passage/index.tsx
fix issue: new stanza button doesn't work after the previous pull request
> Pull Request 2024-10-16 Fix a bug caused by the previous pull request

- src/components/StudyPane/Passage/StanzaBlock.tsx
- src/components/StudyPane/Passage/WordBlock.tsx
Fix bug: parts of stanza become inaccessible when there are more than 4 stanzas on the screen
> Pull Request 2024-10-19 Fix stanza bug

- src/components/StudyPane/Passage/EsvPopover.tsx
- src/lib/actions.ts
- added function to set the fetched esv data into local storage to fetch api once during study load
- subsequent renders of the frontend during structure changes to stanza/strophes no longer need to load from the api, but local storage instead = more reliable availability of esv Data
> Esv popover bug

- src/app/coming-soon/page.tsx
top : i recommend re-wording to:
1) "Pardon our dust—we’re crafting a digital experience worth the wait. Launching soon!" or
2) "our web app is almost ready to help you unearth the poetic treasures hidden in the Bible. Coming soon!"
> update coming-soon page message as per Helen's suggestion

- src/components/Modals/SmartHighlight.tsx
- src/components/StudyPane/Header/LanguageSwitcher.tsx
- src/components/StudyPane/InfoPane/Motif/Root.tsx
- src/hooks/useDragToSelect.tsx
> Pull Request 2024-12-07 Language switch style change, Add warning modal on smart hightlight under motif

- src/components/CountDownTimer/index.tsx
Update launch time to 2025.01.07 19:00
> fix: launch date

- src/components/StudyPane/Passage/index.tsx
- src/components/StudyPane/Toolbar/Buttons.tsx
- src/hooks/useDragToSelect.tsx
first version of ctrl+A to select all feature
> Pull Request 2025-02-17 ctrl+A select all feature

- src/app/dashboard/public/page.tsx
- src/components/Tables/Public.tsx
- src/components/Tables/SortableColumnHeader.tsx
This PR is just for preview. If the approach looks good, will create another PR that applies the changes to recent and public tables based on the latest main branch.
> preview sortable column

- src/app/dashboard/home/page.tsx
- src/components/Tables/Recent.tsx
- src/components/Tables/SortableColumnHeader.tsx
- src/lib/actions.ts
- src/lib/data.ts
- add hover highlight to sortable column header
- add created at to recent tables
- make recent table sortable by columns: name, passage, createdAt, updatedAt
> make recent table sortable by columns

- src/components/StudyPane/Passage/WordBlock.tsx
The indented block is not aligned with uniform width word block. Fixing the size for indented block to keep it aligned. Sending to Toby for user testing
> fix indent block size

- src/components/Tables/Public.tsx
- src/lib/actions.ts
- src/lib/data.ts
refactor `Public.tsx`:
- make `Public.tsx` a client component so we can display time in client's timezone
- refactor fetch clerk user and public studies in `fetchPublicStudies` in `action.ts`
> refactor Public.tsx to support local timezone display
